variables:
  API_TOKEN: $DEPLOYMENT_TOKEN
  APP_PATH: '$CI_PROJECT_DIR'
  OUTPUT_PATH: '$CI_PROJECT_DIR/build'

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - build
  - deploy

build_job:
  image: node:16
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - ./build

deploy_job:
  environment: production
  stage: deploy
  image: mcr.microsoft.com/azure-static-web-apps-deploy:latest
  script:
    - echo "Deploying to Azure Static Web App..."
    - npx azure-static-web-apps-deploy --app-location "/" --api-location "./api" --output-location "build" --token $API_TOKEN
